name: "OctoFlow"
description: "Render a Mermaid job graph directly in the workflow summary."
author: "Evan"
inputs:
  github-token:
    description: "Token used to call the GitHub Actions API."
    required: true
  artifact:
    description: "Upload the normalized `octoflow.json` artifact when true."
    required: false
    default: "true"
  graph:
    description: "Graph format to render (only `mermaid` supported today)."
    required: false
    default: "mermaid"
  title:
    description: "Heading to show above the summary graph."
    required: false
    default: "OctoFlow"
runs:
  using: "node20"
  main: "dist/main.js"
  post: "dist/post.js"
  post-if: "always()"
branding:
  icon: "activity"
  color: "purple"
